"$schema" = "https://starship.rs/config-schema.json"

# プロンプトの前に改行を追加
add_newline = true

palette = 'my_colors'

format = """
$os$custom$shell\
$directory\
$git_branch\
$git_commit\
$git_status\
$python\
$nodejs\
$bun\
$rust\
[](fg:prev_bg)\
$fill\
$time$cmd_duration$status[](fg:prev_bg)
$character\
"""

[ palettes . my_colors ]
text_fg = '#ffffff'

os_bg = '#374362'
windows_bg = '#3a6cff'
macos_bg = '#9dabd1'
macos_fg = '#0b1010'
ubuntu_bg = '#C14362'
debian_bg = '#d0074f'

shell_bg = '#9dabd1'
powershell_bg = '#2a415f'
cmd_bg = '#808080'
zsh_bg = '#4c6fcf'
bash_bg = '#ffcf84'

dir_bg = '#ffa857'

git_bg = '#6e5494'

python_bg = '#2dba2d'
rust_bg = '#a2300c'
node_bg = '#2257e6'
bun_bg = '#474A4F'

status_bg = '#FF4362'
status_fg = '#ffffff'
time_bg = '#5e6c87'
cmd_duration_bg = '#9cabd0'

[fill]
symbol = " "
style = "bg:transparent fg:transparent"

[line_break]
disabled = true

[character]
success_symbol = "[ >>](bold white)"
error_symbol = "[ >>](bold white)"

[os]
disabled = false
format = '[$custom$symbol]($style)'

[os.symbols]
Windows = "[](fg:windows_bg)[ ](bold bg:windows_bg)"
Macos = "[](fg:macos_bg)[ ](bold bg:macos_bg fg:macos_fg)"
Ubuntu = "[](fg:ubuntu_bg)[ ](bold bg:ubuntu_bg)"
Debian = "[](fg:debian_bg)[ ](bold bg:debian_bg)"

[custom.wsl]
os = "linux"
when = "uname -r | grep WSL"
format = "[WSL](bold bg:prev_bg fg:prev_fg)"

[shell]
disabled = false
format = "$indicator"
powershell_indicator = "[](fg:prev_bg bg:powershell_bg)[ pwsh ](bg:powershell_bg fg:text_fg)"
zsh_indicator = "[](fg:prev_bg bg:zsh_bg)[ zsh ](bg:zsh_bg fg:text_fg)"
bash_indicator = "[](fg:prev_bg bg:bash_bg)[ bash ](bg:bash_bg fg:text_fg)"
cmd_indicator = "[](fg:prev_bg bg:cmd_bg)[ cmd ](bg:cmd_bg fg:text_fg)"

[directory]
style = "bg:dir_bg fg:text_fg"
read_only_style = "bg:dir_bg fg:text_fg"
format = "[](fg:prev_bg bg:dir_bg)[ \uf07c ( )($read_only) $path ]($style)"
read_only = " \uf023"
truncation_length = 99
truncate_to_repo = false

[git_branch]
symbol = " "
style = "bg:git_bg fg:text_fg"
format = "[](fg:prev_bg bg:git_bg)[ $symbol $branch ]($style)"
only_attached = true

[git_commit]
style = "bg:git_bg fg:text_fg"
format = "[](fg:prev_bg bg:git_bg)[   $hash$tag]($style)"

[git_status]
style = "bg:git_bg fg:text_fg"
format = '[($ahead_behind)( $staged)( $untracked)( $modified)( $deleted)]($style)'
up_to_date = "✔"
ahead = ' $count'
behind = ' $count'
diverged = ' $behind_count $ahead_count'

staged = "+$count"

modified = " $count"
untracked = " $count"
deleted = "󰗨 $count"
renamed = "󰑓 $count"

stashed = ""

[nodejs]
symbol = "󰎙"
style = "bg:node_bg fg:text_fg"
format = "[](fg:prev_bg bg:node_bg)[ $symbol ($version) ]($style)"
version_format = " v${raw}"

[python]
symbol = ""
style = "bg:python_bg fg:text_fg"
format = "[](fg:prev_bg bg:python_bg)[ $symbol ($version) ]($style)"
version_format = " v${raw}"
detect_folders = [".venv", "venv"]

[bun]
symbol = ""
style = "bg:bun_bg fg:text_fg"
format = "[](fg:prev_bg bg:bun_bg)[ $symbol ( $version) ]($style)"

[rust]
symbol = ""
style = "bg:rust_bg fg:text_fg"
format = "[](fg:prev_bg bg:rust_bg)[ $symbol ($version) ]($style)"
version_format = " v${raw}"
detect_files = ['Cargo.toml']
detect_folders = ['src-tauri']

[time]
disabled = false
style = "bg:time_bg fg:text_fg"
time_format = "%Y/%m/%d %H:%M"
format = "[](fg:time_bg)[ 󰃰 $time]($style)"

[cmd_duration]
disabled = false
style = "bg:cmd_duration_bg fg:text_fg"
format = "[](fg:cmd_duration_bg bg:prev_bg)[ $duration ]($style)"
min_time = 0

[status]
symbol = "Err"
style = "bg:status_bg fg:status_fg"
format = "[](bg:prev_bg fg:status_bg)[ $symbol]($style)"
disabled = false
