"$schema" = "https://starship.rs/config-schema.json"

# ãƒ—ãƒ­ãƒ³ãƒ—ãƒˆã®å‰ã«æ”¹è¡Œã‚’è¿½åŠ 
add_newline = true

palette = 'my_colors'

format = """
[î‚¶](fg:dir_bg)\
$directory\
$git_branch\
$git_status\
$rust\
$nodejs\
$python\
$bun\
$status\
[î‚°](fg:prev_bg)
$line_break\
$character\
"""

right_format = """
"""

[ palettes . my_colors ]
text_fg = 'white'
dir_bg = '#ffa857'
git_bg = '#6e5494'
python_bg = '#2dba2d'
rust_bg = '#FCA17D'
node_bg = '#3C873A'
bun_bg = '#474A4F'
status_bg = '#FF8080'
status_fg = '#ff0000'
time_bg = '#474A4F'

[line_break]
disabled = true

[directory]
style = "bg:dir_bg fg:text_fg"
read_only_style = "bg:dir_bg fg:text_fg"
format = "[ \uf07c ( )($read_only) $path ]($style)"
read_only = " \uf023"
truncation_length = 99
truncate_to_repo = false

[git_branch]
symbol = "ïˆî‚ "
style = "bg:git_bg fg:text_fg"
format = "[î‚°](fg:prev_bg bg:git_bg)[ $symbol $branch ]($style)"

[git_status]
style = "bg:git_bg fg:text_fg"
format = '[($ahead_behind )(($staged)$modified )($untracked $deleted )]($style)'
up_to_date = "âœ”"
modified = "ï„"
untracked = "î©¿"
deleted = "ó°—¨"
renamed = "ó°‘“"
stashed = ""

[rust]
symbol = "ðŸ¦€"
style = "bg:rust_bg fg:text_fg"
format = "[î‚°](fg:prev_bg bg:rust_bg)[ $symbol ($version) î‚°]($style)"

[nodejs]
symbol = "ó°Ž™"
style = "bg:node_bg fg:text_fg"
format = "[î‚°](fg:prev_bg bg:node_bg)[ $symbol ($version) ]($style)"

[python]
symbol = "îœ¼"
style = "bg:python_bg fg:text_fg"
format = "[î‚°](fg:prev_bg bg:python_bg)[ $symbol ($version) ]($style)"
version_format = "Python ${raw}"

[bun]
symbol = "ðŸ¥Ÿ"
style = "bg:bun_bg fg:text_fg"
format = "[î‚°](fg:prev_bg bg:bun_bg)[ $symbol ($version) ]($style)"

[status]
symbol = "Error"
style = "bg:status_bg fg:status_fg"
format = "[î‚°](fg:prev_bg bg:status_bg)[ $symbol ]($style)"
disabled = false

[character]
success_symbol = "[ >>](bold white)"
error_symbol = "[ >>](bold white)"

[time]
disabled = false
format = "[î‚¶ ó°¥” $time]($style)"